//#undef LED_HAL_USE_P98X3 // Grove CHAINABLE LED etc.
//#undef LED_HAL_USE_MY9221
//#undef LED_HAL_USE_NEO_PIXEL
#ifdef ARDUINO_ARCH_RP2040
//#undef LED_HAL_USE_P98X3 // Grove CHAINABLE LED etc.
//#undef LED_HAL_USE_MY9221
#undef LED_HAL_USE_NEO_PIXEL
#else /* ARDUINO_ARCH_RP2040 */
//#undef LED_HAL_USE_P98X3 // Grove CHAINABLE LED etc.
//#undef LED_HAL_USE_MY9221
//#undef LED_HAL_USE_NEO_PIXEL
#endif /* ARDUINO_ARCH_RP2040 */